### ISSUE TITLE
Undeclared dependency on npg_tracking

### ISSUE THREAD

**Issue by keithj** [wtsi-npg/genotyping#395]
There is an undeclared dependency on npg_tracking via [WTSI::NPG::Genotyping::VCF::ReferenceFinder](https://github.com/wtsi-npg/genotyping/blob/devel/src/perl/lib/WTSI/NPG/Genotyping/VCF/ReferenceFinder.pm#L11). This causes VCF tests to fail.

**Comment by iainrb** [comment]
Fixed by commit https://github.com/wtsi-npg/genotyping/commit/ca23914c861a35291a4eaf540a7e6883946cf7bd on 9 Feb 2016.
