### ISSUE TITLE
Illuminus workflow doesn't check for required argument plex_manifest

### ISSUE THREAD

**Issue by keithj** [wtsi-npg/genotyping#434]
If the user forgets this required argument the pipeline will still run for a long time and then fail
later:

````
Attribute (plex_manifest) does not pass the type constraint because: Validation failed for 'Str'
with value undef at accessor WTSI::NPG::Genotyping::QC::Identity::plex_manifest
(defined at /software/gapi/pkg/genotyping/1.13.1/lib/perl5/WTSI/NPG/Genotyping/QC/Identity.pm line 105) 
````

**Comment by keithj** [comment]
The workflow removes `plex_manifest` from the arguments to the workflow and then adds it back when calling certain tasks, only if a `vcf` argument is also supplied. The workflow therefore always fail as there id no vcf to supply.

**Comment by iainrb** [comment]
The zcall workflow has a similar issue. Fix for illuminus is now passing tests, will implement a similar one for zcall.
